version: "3"  
services:  
  prometheus:
    image: prom/prometheus:latest
    ports:
     - 9090:9090 
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
     - "./rules.yaml:/etc/prometheus/rules.yaml"
  alertmanager:
    image: prom/alertmanager:latest
    command: "--config.file=/alertmanager.yaml --web.external-url=http://158.177.121.27:9093"
    volumes:
      - "./alertmanager.yaml:/alertmanager.yaml"  
    ports:
     - 9093:9093
  node:
    build: ./node_exporter
  grafana:
    image: grafana/grafana
    ports:
     - 3000:3000
  mongo:
    image: mongo
  app:
    build: ./app
    ports:
     - 5000:5000
     - 8000:8000
